version: "3.5"

services:
  traefik:
    image: traefik:v2.9
    container_name: traefik
    command:
      # - --log.level=DEBUG
      - --api.dashboard
      - --api.insecure
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --entrypoints.http.address=:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - nizhib
    ports:
      - "80:80"
      - "8080:8080"
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.rule=Host(`traefik.localhost`)
      - traefik.http.routers.api.entrypoints=http
      - traefik.http.routers.api.service=api@internal

  grammar-front:
    build:
      context: front
      dockerfile: Dockerfile
    networks:
      nizhib:
        aliases:
          - grammar.localhost
    expose:
      - 80
    labels:
      - traefik.enable=true
      - traefik.http.routers.grammar-front.entrypoints=http
      - traefik.http.routers.grammar-front.rule=Host(`grammar.localhost`)

  grammar-back:
    build:
      context: back
      dockerfile: Dockerfile
    networks:
      - nizhib
    expose:
      - 5000
    labels:
      - traefik.enable=true
      - traefik.http.routers.grammar-back.entrypoints=http
      - traefik.http.routers.grammar-back.rule=Host(`grammar.localhost`) && PathPrefix(`/api`)
      - traefik.http.routers.grammar-back.middlewares=remove-api
      - traefik.http.middlewares.remove-api.stripprefix.prefixes=/api

networks:
  nizhib:
    name: nizhib
